### ISSUE TITLE
API Blueprint from request specs

### ISSUE THREAD

**Issue by nullstyle** [stellar/horizon-importer#2]
Use something like https://github.com/playround/rspec_api_blueprint to partially automate the production of api blueprint documentation.

**Comment by malandrina** [comment]
If you're not feeling totally committed to API Blueprint as a tool for providing API docs you might take a look at [prmd](https://github.com/interagent/prmd). prmd generates API documentation from [JSON Schema](http://json-schema.org/) documents.

Defining JSON Schema schemas for endpoint responses rather than using a tool like `rspec_api_blueprint` would allow you to avoid conforming to the tool's DSL in request specs and enforce separation of the doc-generating and system-testing concerns. The big downside of this approach is that you do have to write and maintain schemas describing the responses of all your API endpoints, and you have to define a workflow for keeping the generated docs up to date.

If you decide you'd like to try the JSON Schema approach, I'd be happy to help write the schemas.

**Comment by nullstyle** [comment]
@malandrina Thanks for the heads up!  prmd is a new one to me.  I'll take a look at it.  

At present, the primary reason we chose apiary is that they have a decent enough UI that requires no effort, design-wise, on our part.  I'm not super attached to it, and eventually would love to have truly stellar (sorry couldn't help myself) api docs.

My current plan (would love feedback), is to express the "model" sections in our blueprints with json schema, but express the response examples using concrete json.  In my experience and in my opinion, it's easier for someone to start with a concrete example than it is with just a plain schema.

For (a trivial) example:

```json
{
  "txHash": "802da5683737972e5a0a6d8d4960bb43a7be64a1dbc00549eeb31729f94c75f2"
}

```

is just a little bit easier to incorporate into a first impression than:

```json
{
  "type": "object",
  "properties": {
    "txHash": {
      "type": "string"
    },
  },
  "required": ["txHash"]
}
```

The goal with using a tool like rspec_api_blueprint (although I imagine I'll have to build a simple custom tool) is mostly to ease the maintenance of those example responses.

Thanks!
-Scott
